package models

import (
	"time"
)

// HTTPExchange represents a complete HTTP request-response pair
// This is the fundamental unit of analysis in security testing
type HTTPExchange struct {
	ID        string       `json:"id" jsonschema:"description=Unique exchange ID (e.g., exch-123)"`
	Request   RequestPart  `json:"request" jsonschema:"description=HTTP request details"`
	Response  ResponsePart `json:"response" jsonschema:"description=HTTP response details"`
	Timestamp time.Time    `json:"timestamp" jsonschema:"description=Unix timestamp when exchange occurred"`
}

// RequestPart represents the HTTP request portion
type RequestPart struct {
	Method  string            `json:"method" jsonschema:"description=HTTP method,enum=GET,enum=POST,enum=PUT,enum=DELETE,enum=PATCH"`
	URL     string            `json:"url" jsonschema:"description=Full URL including protocol and path"`
	Headers map[string]string `json:"headers,omitempty" jsonschema:"description=Request headers"`
	Body    string            `json:"body,omitempty" jsonschema:"description=Request body (truncated if large)"`
}

// ResponsePart represents the HTTP response portion
type ResponsePart struct {
	StatusCode int               `json:"status_code" jsonschema:"description=HTTP status code,minimum=100,maximum=599"`
	Headers    map[string]string `json:"headers,omitempty" jsonschema:"description=Response headers"`
	Body       string            `json:"body,omitempty" jsonschema:"description=Response body (truncated if large)"`
}

// Observation represents a security-relevant fact
// Key principle: Observation = FACT, not interpretation
// NOT common patterns like JWT or session string - these are baseline
//
// Technical fields (id, exchange_ids, created_at) are populated by Go code, not LLM.
// Business fields (what, where, why) are generated by LLM.
// Hint is added by Strategist during deduplication/analysis.
type Observation struct {
	ID          string    `json:"id,omitempty" jsonschema:"description=Auto-generated unique observation ID (e.g., obs-123)"`
	ExchangeIDs []string  `json:"exchange_ids,omitempty" jsonschema:"description=Auto-populated references to HTTPExchanges (single from Analyst, multiple from Strategist deduplication)"`
	What        string    `json:"what" jsonschema:"description=EXACT fact observed (no interpretation),required"`
	Where       string    `json:"where" jsonschema:"description=Precise location with value,required"`
	Why         string    `json:"why" jsonschema:"description=Why this fact is useful for understanding/attacking,required"`
	Hint        string    `json:"hint,omitempty" jsonschema:"description=Actionable guidance from Strategist"`
	CreatedAt   time.Time `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when observation was created"`
}

// Lead represents an actionable security lead (replaces Hypothesis + Finding)
// Technical fields (id, created_at) are populated by Go code, not LLM.
// Business fields (title, actionable_step, pocs) are generated by LLM.
type Lead struct {
	ID             string     `json:"id,omitempty" jsonschema:"description=Auto-generated unique lead ID (e.g., lead-456)"`
	Title          string     `json:"title" jsonschema:"description=Short title (max 10 words),required"`
	ActionableStep string     `json:"actionable_step" jsonschema:"description=Concrete testing step,required"`
	PoCs           []PoCEntry `json:"pocs,omitempty" jsonschema:"description=Human-readable PoC instructions"`
	CreatedAt      time.Time  `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when lead was created"`
	// REMOVED: CanAutoVerify, AutoVerified, VerificationResult - no auto-verification
}

// PoCEntry represents a proof-of-concept instruction (human-readable)
type PoCEntry struct {
	Payload string `json:"payload" jsonschema:"description=Testing instruction (curl, description, steps)"`
	Comment string `json:"comment" jsonschema:"description=Explanation of what this PoC tests"`
}

// Connection represents a relationship between two entities
// Technical fields (from, to, created_at) are populated by Go code, not LLM.
// Business field (reason) is generated by LLM.
type Connection struct {
	From      string    `json:"from" jsonschema:"description=First entity ID (e.g., obs-1),required"`
	To        string    `json:"to" jsonschema:"description=Second entity ID (e.g., obs-3),required"`
	Reason    string    `json:"reason" jsonschema:"description=Why they are connected,required"`
	CreatedAt time.Time `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when connection was created"`
}

// BigPicture represents high-level understanding of the target (LLM-driven updates)
type BigPicture struct {
	Description string `json:"description" jsonschema:"description=High-level app description in Markdown format"`
}

// BigPictureImpact represents a suggested update to the big picture
// All fields are optional because this is entirely generated by LLM
type BigPictureImpact struct {
	Field  string `json:"field,omitempty" jsonschema:"description=Which field to update (description)"`
	Value  string `json:"value,omitempty" jsonschema:"description=New value for the big picture"`
	Reason string `json:"reason,omitempty" jsonschema:"description=Why this update is needed"`
}

// SiteMapEntry represents an entry in the site map (Burp-style)
type SiteMapEntry struct {
	ID         string       `json:"id" jsonschema:"description=Unique site map entry ID"`
	ExchangeID string       `json:"exchangeID"`
	Method     string       `json:"method" jsonschema:"description=HTTP method"`
	URL        string       `json:"url" jsonschema:"description=Full URL"`
	Comment    string       `json:"comment" jsonschema:"description=LLM-generated comment about this entry"`
	Request    RequestPart  `json:"request" jsonschema:"description=Request portion"`
	Response   ResponsePart `json:"response" jsonschema:"description=Response portion"`
	Children   []string     `json:"children,omitempty" jsonschema:"description=Child IDs for hierarchy"`
	CreatedAt  time.Time    `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when entry was created"`
}
