package models

import (
	"time"
)

// HTTPExchange represents a complete HTTP request-response pair
// This is the fundamental unit of analysis in security testing
type HTTPExchange struct {
	ID        string       `json:"id" jsonschema:"description=Unique exchange ID (e.g., exch-123)"`
	Request   RequestPart  `json:"request" jsonschema:"description=HTTP request details"`
	Response  ResponsePart `json:"response" jsonschema:"description=HTTP response details"`
	Timestamp time.Time    `json:"timestamp" jsonschema:"description=Unix timestamp when exchange occurred"`
}

// RequestPart represents the HTTP request portion
type RequestPart struct {
	Method  string            `json:"method" jsonschema:"description=HTTP method,enum=GET,enum=POST,enum=PUT,enum=DELETE,enum=PATCH"`
	URL     string            `json:"url" jsonschema:"description=Full URL including protocol and path"`
	Headers map[string]string `json:"headers,omitempty" jsonschema:"description=Request headers"`
	Body    string            `json:"body,omitempty" jsonschema:"description=Request body (truncated if large)"`
}

// ResponsePart represents the HTTP response portion
type ResponsePart struct {
	StatusCode int               `json:"status_code" jsonschema:"description=HTTP status code,minimum=100,maximum=599"`
	Headers    map[string]string `json:"headers,omitempty" jsonschema:"description=Response headers"`
	Body       string            `json:"body,omitempty" jsonschema:"description=Response body (truncated if large)"`
}

// Observation represents a security-relevant fact
// Key principle: Observation = FACT, not interpretation
// NOT common patterns like JWT or session string - these are baseline
//
// Technical fields (id, exchange_ids, created_at) are populated by Go code, not LLM.
// Business fields (what, where, why) are generated by LLM.
// Hint is added by Strategist during deduplication/analysis.
type Observation struct {
	ID          string    `json:"id,omitempty" jsonschema:"description=Auto-generated unique observation ID (e.g., obs-123)"`
	ExchangeIDs []string  `json:"exchange_ids,omitempty" jsonschema:"description=Auto-populated references to HTTPExchanges (single from Analyst, multiple from Strategist deduplication)"`
	What        string    `json:"what" jsonschema:"description=EXACT fact observed (no interpretation),required"`
	Where       string    `json:"where" jsonschema:"description=Precise location with value,required"`
	Why         string    `json:"why" jsonschema:"description=Why this fact is useful for understanding/attacking,required"`
	Type        string    `json:"type,omitempty" jsonschema:"description=Observation type classification (MongoDB ObjectID, JWT Token, Integer ID, UUID, etc.)"`
	Hint        *string   `json:"hint,omitempty" jsonschema:"description=Actionable guidance from Strategist,nullable"`
	CreatedAt   time.Time `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when observation was created"`
}

// Lead represents an actionable security lead (replaces Hypothesis + Finding)
// Technical fields (id, created_at) are populated by Go code, not LLM.
// Business fields (title, actionable_step, pocs) are generated by LLM.
type Lead struct {
	ID             string     `json:"id,omitempty" jsonschema:"description=Auto-generated unique lead ID (e.g., lead-456)"`
	Title          string     `json:"title" jsonschema:"description=Short title (max 10 words),required"`
	ActionableStep string     `json:"actionable_step" jsonschema:"description=Concrete testing step,required"`
	PoCs           []PoCEntry `json:"pocs,omitempty" jsonschema:"description=Human-readable PoC instructions"`
	CreatedAt      time.Time  `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when lead was created"`
	// REMOVED: CanAutoVerify, AutoVerified, VerificationResult - no auto-verification
}

// PoCEntry represents a proof-of-concept instruction (human-readable)
type PoCEntry struct {
	Payload string `json:"payload,omitempty" jsonschema:"description=Testing instruction (curl, description, steps)"`
	Comment string `json:"comment,omitempty" jsonschema:"description=Explanation of what this PoC tests"`
}

// Connection represents a relationship between two entities
// Technical fields (from, to, created_at) are populated by Go code, not LLM.
// Business field (reason) is generated by LLM.
type Connection struct {
	From      string    `json:"from" jsonschema:"description=First entity ID (e.g., obs-1),required"`
	To        string    `json:"to" jsonschema:"description=Second entity ID (e.g., obs-3),required"`
	Reason    string    `json:"reason" jsonschema:"description=Why they are connected,required"`
	CreatedAt time.Time `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when connection was created"`
}

// BigPicture represents high-level understanding of the target (LLM-driven updates)
type BigPicture struct {
	Description string `json:"description" jsonschema:"description=High-level app description in Markdown format"`
}

// BigPictureImpact represents a suggested update to the big picture
// All fields are optional because this is entirely generated by LLM
type BigPictureImpact struct {
	Field  string `json:"field,omitempty" jsonschema:"description=Which field to update (description)"`
	Value  string `json:"value,omitempty" jsonschema:"description=New value for the big picture"`
	Reason string `json:"reason,omitempty" jsonschema:"description=Why this update is needed"`
}

// SystemArchitecture represents the reconstructed system architecture
// Built by Architect agent from raw observations and site map
type SystemArchitecture struct {
	TechStack string     `json:"tech_stack" jsonschema:"description=Detected technology stack (e.g., 'MongoDB, Node.js/Express, Auth via JWT')"`
	DataFlows []DataFlow `json:"data_flows" jsonschema:"description=Data flow chains showing how data moves through routes"`
}

// DataFlow represents how data flows through a chain of routes
// Key insight: Data has sources (upload forms), transformations (DB operations), and sinks (downloads)
type DataFlow struct {
	Route         string `json:"route" jsonschema:"description=Route chain (e.g., 'POST /api/shop/ --> GET /api/shop/:id --> DELETE /api/shop/:id')"`
	InferredLogic string `json:"inferred_logic" jsonschema:"description=Inferred backend logic (e.g., 'User uploads picture -> Picture saved to DB -> User can retrieve picture via id in URL')"`
}

// SiteMapEntry represents an entry in the site map (Burp-style)
// Architecture: Lightweight view with TrafficDigest + ExchangeID reference
// Raw HTTP data is stored in InMemoryGraph and accessible via getExchange tool
type SiteMapEntry struct {
	ID         string `json:"id" jsonschema:"description=Unique site map entry ID"`
	ExchangeID string `json:"exchange_id" jsonschema:"description=Reference to InMemoryGraph for raw HTTP data"`
	Method     string `json:"method" jsonschema:"description=HTTP method"`
	URL        string `json:"url" jsonschema:"description=Full URL"`

	// Digest is the architectural summary (lightweight view)
	// Generated by Architect agent to understand system structure
	Digest *TrafficDigest `json:"digest,omitempty" jsonschema:"description=Architectural summary with route signature, inputs/outputs, tech stack,nullable"`

	// Hierarchy management
	Children  []string  `json:"children,omitempty" jsonschema:"description=Child IDs for hierarchy"`
	CreatedAt time.Time `json:"created_at,omitempty" jsonschema:"description=Auto-populated Unix timestamp when entry was created"`
}

// TrafficDigest represents an architectural summary ("passport") of an HTTP exchange
// Generated by Architect agent to understand the system's data flow and technology stack
type TrafficDigest struct {
	// RouteSignature is the normalized route signature without query parameters
	// Examples: "POST /api/users", "GET /files/{id}", "DELETE /api/shop/:id"
	RouteSignature string `json:"route_signature" jsonschema:"description=Normalized route signature (method + path, no query params),required"`

	// Summary is a concise description of the route's logic for context understanding
	// Examples: "User login -> returns JWT token", "Upload file -> save to DB -> return file ID"
	Summary string `json:"summary" jsonschema:"description=Brief description of route logic and purpose,required"`

	// Inputs lists data fields sent by the client (request data)
	// Helps understand what data the system accepts and how it's structured
	Inputs []DataField `json:"inputs" jsonschema:"description=Data fields sent by the client in the request"`

	// Outputs lists data fields returned by the server (response data)
	// Helps understand what data the system exposes and how it's structured
	Outputs []DataField `json:"outputs" jsonschema:"description=Data fields returned by the server in the response"`

	// TechStackHints contains discovered technology markers from the exchange
	// Examples: ["MongoDB (ObjectId format)", "JWT authentication", "Express.js"]
	TechStackHints []string `json:"tech_stack_hints" jsonschema:"description=Technology markers detected in this exchange"`
}

// DataField represents a specific data field with its location and type information
// Used in TrafficDigest to document the structure of request/response data
type DataField struct {
	// Name is the field name or identifier
	// Examples: "user_id", "Authorization", "q", "file", "token"
	Name string `json:"name" jsonschema:"description=Field name or identifier,required"`

	// Location specifies where the field is found in the HTTP exchange
	// Values: "query", "body_json", "body_form", "header", "path", "cookie"
	Location string `json:"location" jsonschema:"description=Field location in HTTP message,enum=query,enum=body_json,enum=body_form,enum=header,enum=path,enum=cookie,required"`

	// DataType indicates the semantic type/format of the data
	// Values: "integer", "string", "mongo_object_id", "jwt", "uuid", "base64", "email", "boolean"
	DataType string `json:"data_type" jsonschema:"description=Semantic data type classification,enum=integer,enum=string,enum=mongo_object_id,enum=jwt,enum=uuid,enum=base64,enum=email,enum=boolean,required"`
}

// TacticianTask represents a task for the Tactician agent
// Generated by Strategist, executed by Tactician to produce actionable leads
type TacticianTask struct {
	ObservationIDs []string `json:"observation_ids"`    // List of observation IDs to reference
	Description    string   `json:"description"`        // Task description for Tactician
	DataFlow       string   `json:"dataflow,omitempty"` // Which data flow chain this targets
}
